import enum

class UserRole(str, enum.Enum):
    CONTRACTOR = "CONTRACTOR"
    RE = "RE"
    CLIENT = "CLIENT"

class WorkflowState(str, enum.Enum):
    DRAFT = "DRAFT"
    SUBMITTED = "SUBMITTED"
    AI_PRE_REVIEW = "AI_PRE_REVIEW"
    PENDING_INSPECTION = "PENDING_INSPECTION"
    INSPECTION_IN_PROGRESS = "INSPECTION_IN_PROGRESS"
    INSPECTION_ACCEPTED = "INSPECTION_ACCEPTED"
    INSPECTION_REJECTED = "INSPECTION_REJECTED"
    QUANTITY_SUBMITTED = "QUANTITY_SUBMITTED"
    RE_APPROVED = "RE_APPROVED"
    RE_REJECTED = "RE_REJECTED"
    CLIENT_REVIEW = "CLIENT_REVIEW"
    CLIENT_APPROVED = "CLIENT_APPROVED"
    CLIENT_REJECTED = "CLIENT_REJECTED"
    IPC_ELIGIBLE = "IPC_ELIGIBLE"
    IPC_INCLUDED = "IPC_INCLUDED"

class InspectionDecision(str, enum.Enum):
    ACCEPT = "ACCEPT"
    REJECT = "REJECT"
    CONDITIONAL = "CONDITIONAL"

class ObservationSeverity(str, enum.Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"

class ObservationCategory(str, enum.Enum):
    QUALITY = "QUALITY"
    SAFETY = "SAFETY"
    SPECIFICATION = "SPECIFICATION"
    WORKMANSHIP = "WORKMANSHIP"
    DOCUMENTATION = "DOCUMENTATION"

class IpcStatus(str, enum.Enum):
    DRAFT = "DRAFT"
    ISSUED = "ISSUED"
    CERTIFIED = "CERTIFIED"
    PAID = "PAID"

class AuditAction(str, enum.Enum):
    AUTH_LOGIN = "AUTH_LOGIN"
    CR_CREATED = "CR_CREATED"
    CR_SUBMITTED = "CR_SUBMITTED"
    EVIDENCE_UPLOADED = "EVIDENCE_UPLOADED"
    AI_REVIEW_GENERATED = "AI_REVIEW_GENERATED"
    INSPECTION_STARTED = "INSPECTION_STARTED"
    OBSERVATION_CREATED = "OBSERVATION_CREATED"
    OBSERVATION_UPDATED = "OBSERVATION_UPDATED"
    INSPECTION_DECIDED = "INSPECTION_DECIDED"
    QUANTITY_SUBMITTED = "QUANTITY_SUBMITTED"
    RE_QUANTITY_APPROVED = "RE_QUANTITY_APPROVED"
    RE_QUANTITY_REJECTED = "RE_QUANTITY_REJECTED"
    CLIENT_REVIEW_STARTED = "CLIENT_REVIEW_STARTED"
    CLIENT_APPROVED = "CLIENT_APPROVED"
    CLIENT_REJECTED = "CLIENT_REJECTED"
    IPC_GENERATED = "IPC_GENERATED"
    IPC_UPDATED = "IPC_UPDATED"
